Repository WLVerse/FlexEngine, pull requests merged in 2024-10, with the labels that each got.

#61 <Refactor> Finalizing the update matrix with relevant checks and error handling, Rewriting openglspriterenderer, and modifying debugrenderer and deleted missing tex
  FlexEngine/FlexEngine.vcxproj
  FlexEngine/src/FlexEngine/Core/window.cpp
  FlexEngine/src/FlexEngine/Renderer/DebugRenderer/debugrenderer.cpp
  FlexEngine/src/FlexEngine/Renderer/DebugRenderer/debugrenderer.h
  FlexEngine/src/FlexEngine/Renderer/OpenGL/opengldebugrenderer.cpp
  FlexEngine/src/FlexEngine/Renderer/OpenGL/opengldebugrenderer.h
  FlexEngine/src/FlexEngine/Renderer/OpenGL/openglspriterenderer.cpp
  FlexEngine/src/FlexEngine/Renderer/OpenGL/openglspriterenderer.h
  MicroChess/assets/images/misc/wireframe_darkbg.png
  MicroChess/assets/images/misc/wireframe_darktile.png
  MicroChess/assets/images/misc/wireframe_whitetile.png
  MicroChess/assets/shaders/test.frag
  MicroChess/assets/shaders/test.vert
  MicroChess/imgui.ini
  MicroChess/src/BattleSystems/physicssystem.cpp
  MicroChess/src/Components/rendering.cpp
  MicroChess/src/Components/rendering.h
  MicroChess/src/Layers/base.cpp
  MicroChess/src/Layers/imgui_debug.cpp
  MicroChess/src/Layers/overworld.cpp
  MicroChess/src/Physics/box2d.cpp
  MicroChess/src/Renderer/sprite2d.cpp
  MicroChess/src/Renderer/sprite2d.h
Labels: documentation

#80 <Update> Post-processing pipeline finalized, working on batching
  FlexEngine/assets/shader/Shared.vert
  FlexEngine/assets/shader/bloom/bloom_blur_horizontal.frag
  FlexEngine/assets/shader/bloom/bloom_blur_vertical.frag
  FlexEngine/assets/shader/bloom/bloom_bright_extraction.frag
  FlexEngine/assets/shader/bloom/bloom_final_composite.frag
  FlexEngine/assets/shader/bloom/bloom_gaussian_blurD.frag
  FlexEngine/assets/shader/bloom/bloom_gaussian_blurN.frag
  FlexEngine/src/FlexEngine/Core/window.cpp
  FlexEngine/src/FlexEngine/Renderer/OpenGL/openglspriterenderer.cpp
  FlexEngine/src/FlexEngine/Renderer/OpenGL/openglspriterenderer.h
  MicroChess/assets/prefabs/Black Bishop.flxprefab
  MicroChess/assets/prefabs/Black Knight.flxprefab
  MicroChess/assets/prefabs/Black Pawn.flxprefab
  MicroChess/assets/prefabs/White King.flxprefab
  MicroChess/assets/prefabs/White Queen.flxprefab
  MicroChess/assets/shaders/GaussianBlur.frag
  MicroChess/assets/shaders/GaussianBlur.vert
  MicroChess/assets/shaders/batchtexture.frag
  MicroChess/assets/shaders/batchtexture.vert
  MicroChess/assets/shaders/brightness.frag
  MicroChess/assets/shaders/brightness.vert
  MicroChess/assets/shaders/finalComposite.frag
  MicroChess/assets/shaders/finalComposite.vert
  MicroChess/assets/shaders/test.frag
  MicroChess/assets/shaders/test.vert
  MicroChess/imgui.ini
  MicroChess/src/Components/rendering.cpp
  MicroChess/src/Components/rendering.h
  MicroChess/src/Editor/componentviewer.h
  MicroChess/src/Editor/editorgui.cpp
  MicroChess/src/Editor/editorgui.h
  MicroChess/src/Layers/base.cpp
  MicroChess/src/Layers/battle.cpp
  MicroChess/src/Layers/overworld.cpp
  MicroChess/src/Renderer/sprite2d.cpp
  MicroChess/src/Renderer/sprite2d.h
Labels: core engine

#88 Update window.cpp
  FlexEngine/src/FlexEngine/Core/window.cpp
Labels: bug
